### ISSUE TITLE
Think about integration with OSM

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Brix#14]
Let's use `osmnx` and think about functions that could make getting data easier. For instance, a function that returns the buffered bounds of the table would be useful.

**Comment by crisjf** [comment]
@doorleyr, I added a `functions.py` file to start building functions to connect to OSM. Feel free to add stuff to it!

**Comment by Claudio9701** [comment]
Hi @crisjf and @doorleyr: I was wondering if I could use something like [UrbanPy](https://el-bid.github.io/urbanpy/) to get the land use value for each cell and `set_geogrid_data()` accordingly. I think that would require a POST endpoint for the table to set the GEOGRID props.

**Comment by crisjf** [comment]
Hi @Claudio9701 I'll have a look at UrbanPy, it seems to be a good suggestion. 

Following the logic that CityScope is using at the moment, the modules don't really edit `GEOGRID` or `GEOGRIDDATA`. `GEOGRID` is only edited when the table is created and `GEOGRIDDATA` is edited from the front end (the table). 

If you wanted to do something like show a heatmap of land value, then what you want is to post a `heatmap` indicator. Check out the `Noise` example here: https://cityscope.media.mit.edu/CS_Brix/examples.html#heatmap-indicator
This indicator posts a random value for each cell.

**Comment by Claudio9701** [comment]
Hi @crisjf, wow I'm surprised with the quick response. I'm playing with cs_brix (it's great and flexible!!)

I was able to update land-use values:

![showcae](https://media.giphy.com/media/1lgK9rb14YHrR2b37y/giphy.gif)

The code is in this [colab](https://colab.research.google.com/drive/1WjDXdYBoSsugDwVF0W5YdhtcN5D9UGj3?usp=sharing), I can add it to functions.py later if you will.

Now I will go grab something to eat, and later I want to continue with section: "Update land-use using OSM data"

**Comment by RELNO** [comment]
@Claudio9701 that's a great idea, and as @crisjf this should probably part of CityScopeJS Grid Editor https://cityscope.media.mit.edu/CS_cityscopeJS/?editor . Since this tool is built in react/js, it might make sense to use a js library to handle OSM requests. I can see similar discussion here https://forum.openstreetmap.org/viewtopic.php?id=24738. I assume the process to be quite simple: 

![image](https://user-images.githubusercontent.com/14296774/101294162-8695cc00-37e3-11eb-80db-f15c96dcfc14.png)

- we create an empty CityScope grid
- take the center point of each grid cell
- shoot a 'ray' onto the OSM landuse under that point  (a more complex process would be to get the normal distribution under the entire cell, but in cells less than ~20m this makes little ROI) 
- sample that point and 'paint' the cell with this landuse

**Comment by Claudio9701** [comment]
Hi @RELNO, yes you're right, I was thinking of this feature as a button or a setting to initialize the grid on CityScopeJS Grid Editor. 
Following the ideas found on the provided link, I was able to set a land use for each grid cell.

At first, I attempt to use a [land use/cover API](https://openlandmap.org/#/?base=Stamen%20(OpenStreetMap)&center=-11.6317,-75.6385&zoom=8&opacity=80&layer=lcv_land.cover_esacci.lc.l4_c&time=2015) but I wasn't lucky to find any that has a great resolution for Lima (the city I'm currently trying to build in CityScope). Also, some [maps servers](https://osmlanduse.org/#14.831156488238616/-77.04076/-12.045/0/) don't have an API.

Finally, I downloaded osm data accordingly to the default landuse labels and get something like this:

![image](https://user-images.githubusercontent.com/24416566/101304613-a68eb500-380e-11eb-960f-e18a30e38cab.png)
Grid, OSM data, and Grid cell centroids

![image](https://user-images.githubusercontent.com/24416566/101314130-e01eea80-3825-11eb-8aa6-8aed6b02438e.png)
Grid centroids colored by Landuse (Residential is default)

The code is in this [colab](https://colab.research.google.com/drive/1WjDXdYBoSsugDwVF0W5YdhtcN5D9UGj3?usp=sharing). The problem is that when I  try to use the `update_landuse` function it resets the grid, maybe I found the bug after a coffee or two :sleeping: :coffee:

Even though I know some javascript I feel more comfortable doing the functionality in Python and then port it to js. I think js libraries that could help a lot are:

- Geodata downloading: query-overpass, overpass-frontend or osm2geojson-lite
- Geodata processing: turf & d3

**Comment by crisjf** [comment]
@Claudio9701 I see the conversation about setting `GEOGRIDDATA` using JS is continuing in the other repo. 

I think it still makes sense to add the functionality to `brix` of posting to `GEOGRIDDATA`. It might be necessary in the future. 

If you wanna go ahead and submit a pull request with the function you wrote I'd be happy to take a look. I might eventually add it as a method of the `Handler` but you can put it in `functions.py` for now.

**Comment by RELNO** [comment]
> I think it still makes sense to add the functionality to brix of posting to GEOGRIDDATA. It might be necessary in the future.

@crisjf worth keeping in mind that edits to the grid from a different source might not be reflected or break the FE, as it has multiple internal dependencies other than the grid itself.

**Comment by Claudio9701** [comment]
@crisjf I've done the pr, with the notes and comments related to the precautions @RELNO said. 

Also I have tested the function on the colab but I didn't make the proper unittest on the tests folder, let my know if it's necessary :hugs:

**Comment by crisjf** [comment]
All set for now. Thanks for contributing @Claudio9701

**Comment by crisjf** [comment]
I opened #19 to integrate this function to the `Handler`.

**Comment by crisjf** [comment]
The last few commits implement two new functions that can be found here:

https://cityscope.media.mit.edu/CS_Brix/functions.html

**Comment by crisjf** [comment]
I'll close this for now and I'll open another issue to do the same with the ACS and with ZBP. 

Since the types defined in `GEOGRID` come with a `NAICS` code, it might be easier to use `ZBP` to infer the land use based on employment. I'll try this and see how it looks.
