### ISSUE TITLE
`geogrid_props` should not be stored in the Indicator

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Brix#4]
Right now, the `Handler` is passing geogrid_pros to each `Indicator` instance. This messes up the logic, as `geogrid_props` is a table property. Also, we are holding one copy of `geogrid_props` per Indicator. Each Indicator should request `geogrid_props` from the `Handler` as needed.

**Comment by crisjf** [comment]
What is the difference between `types` and `static_types` in `Handler.geogrid_props`?

**Comment by doorleyr** [comment]
Types are the 'new' ones the user can add or remove to create their designs. Static types are the ones which already exist on the site before interventions occur. I need to differentiate between these because the front-end only wants to use the 'types' list to create the interface. But the modules still need to know the characteristics of the static ones.

**Comment by crisjf** [comment]
Got it! Thanks for explaining.

**Comment by crisjf** [comment]
This is done. All the heavy lifting in terms of combining `geogrid_data` and `geogrid_props` is now done by the `Handler` class. Each indicator object just needs to specify `Indicator.requires_geometry` and `Indicator.requires_geogrid_props`. See `README.md` for documentation.
