### ISSUE TITLE
Heatmap Indicator example?

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Brix#7]
The README has a heading for heatmap indicator but no content yet. What about including a simple proximity example on the grid (ignoring the road network)? eg. a residential_proximity indicator could return a geojson grid with the same geometry as the geogrid and a property indicating the grid distance to the closest residential grid cell? Let me know what you think and i can work on it.

**Comment by crisjf** [comment]
This is a good idea. I just implemented a park proximity indicator! It turns out we already had a `Noise` indicator as an example so it was pretty straightforward to implement this. 

Check it out and feel free to make edits. I'm leaving the issue open for now just in case you have any questions or comments.
